# Generated by Django 2.1.4 on 2018-12-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastPow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('n', models.IntegerField()),
                ('mod', models.IntegerField()),
                ('power', models.CharField(max_length=200)),
            ],
        ),
    ]
