# Generated by Django 2.1.4 on 2018-12-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_fastpow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastpow',
            name='power',
            field=models.IntegerField(),
        ),
    ]
